### ISSUE TITLE
How can I deploy the repo manually?

### ISSUE THREAD

**Issue by nobody4t** [clauseHQ/demo-clause-ibm-perishable-goods#12]
I try to deploy it as the doc states. But I have no idea about what does toolchain name means.
I do have the blockchain service network. so I wonder if I can deploy it manually. But I can not find the steps. Please help.
<img width="966" alt="screen shot 2019-01-11 at 06 34 42" src="https://user-images.githubusercontent.com/2303377/51003357-5995fb80-1571-11e9-90e9-2201fd152d1c.png">

**Comment by mttrbrts** [comment]
Hi @WandyLau, thanks for your question. 

The toolchain is the DevOps pipeline that will provision and deploy all of the components of the sample for you. Something like 'WandyLauPerishableGoods' would be great.

I recommend that you try the pipeline first and let us know if you have trouble.

**Comment by nobody4t** [comment]
@mttrbrts Thanks for reply. So it is a toolchain name not a real 'tool', right?
I will try again.

**Comment by nobody4t** [comment]
yes, it works. I just thought it was some special tools. Thanks for help.
