### ISSUE TITLE
Doc correction

### ISSUE THREAD

**Issue by markparz** [clauseHQ/demo-clause-ibm-perishable-goods#2]
In Step 1 it is stated "If you have already deployed the Clause sample on IBM Blockchain Platform via the toolchain, you can skip to step 3."

However, I have to do step 2 to create an account in Clause.

**Comment by markparz** [comment]
You also need step 2 to know what is being referred to as the demonstration application in step 4.

**Comment by mttrbrts** [comment]
Also fixed in the guide. Thanks again @markparz
