### ISSUE TITLE
Invalid clause ID

### ISSUE THREAD

**Issue by danny-mejia** [clauseHQ/demo-clause-ibm-perishable-goods#4]
![image](https://user-images.githubusercontent.com/42442504/44488455-c6dadb80-a626-11e8-9787-1236980aa8b1.png)
Getting an invalid clause ID when trying to use the **execution url**

**Comment by mttrbrts** [comment]
Hi @danny-ibm, thanks for raising an issue. 

Please try making a change to your clause and clicking save before trying again. This is known issue that we plan to address shortly.

Our apologies for any inconvenience.
