### ISSUE TITLE
Fails when inviting grower

### ISSUE THREAD

**Issue by jsmoran123G** [clauseHQ/demo-clause-ibm-perishable-goods#5]
![error](https://user-images.githubusercontent.com/42562990/44503108-d3c0f480-a651-11e8-944c-9d94d6f591d8.jpg)

**Comment by mttrbrts** [comment]
Hi @jsmoran123G , thanks for raising an issue.

Can you please provide some more details about your set-up to help us to diagnose your problem?

- Please confirm that your REST Server that get's deployed as part of the build is live and operational
- Has this ever worked for you or are you attempting for the first time?
- Can you share the URL of your demo application?

Also, please feel free to open a chat within the Clause platform if you're more comfortable sharing this information privately. 

Click this button to start a chat.
![image](https://user-images.githubusercontent.com/7544022/44511628-0c8fb680-a6b0-11e8-913a-ad7172812cdc.png)

**Comment by jsmoran123G** [comment]
Hi, not sure how to confirm the Rest server if there are steps documented I
could perform that.

I followed the instructions provided when selected the perishable sample
from my running blockchain, it has not worked I get stuck when launching.

https://api.clause.io/api/clauses/5b7e127bc8d2d7e20f736ff5/execute?access_token=EEH....

Any help would be appreciated.

Thanks,
Jackie

**Comment by mttrbrts** [comment]
Closing. The thread has moved to the Clause support channel
